# Generated by Django 3.1.4 on 2020-12-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=1200, null=True)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
    ]
