# Generated by Django 3.1.4 on 2020-12-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_cartproduct_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.CharField(choices=[('active', 'active'), ('payed', 'payed'), ('done', 'done')], default='active', max_length=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.cartproduct')),
            ],
        ),
    ]
