# Generated by Django 3.1.4 on 2020-12-15 12:41

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201215_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(to='products.Category'),
        ),
    ]
