# Generated by Django 3.1.4 on 2020-12-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201216_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publush',
            field=models.BooleanField(default=True),
        ),
    ]
