# Generated by Django 3.1.4 on 2020-12-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_publush'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='publush',
            new_name='publish',
        ),
    ]
