# Generated by Django 3.1.4 on 2020-12-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0003_manufacturer_country'),
        ('products', '0013_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manufacturers.manufacturer'),
        ),
    ]
