# Generated by Django 3.1.4 on 2020-12-21 17:46

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20201218_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='EUR', max_digits=14, null=True, verbose_name='Price'),
        ),
    ]
